version: "3.1"
services:
  mongo:
    build: mongo
    restart: always
    ports:
    - 127.0.0.1:27017:27017
    secrets:
    - root_pass
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/root_pass
  mongo-express:
    build: mongo-express
    restart: always
    ports:
    - 127.0.0.1:8081:8081
    secrets:
    - root_pass
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD_FILE: /run/secrets/root_pass
secrets:
  root_pass:
    file: ./root.txt
